import { createOpenAPI } from 'fumadocs-openapi/server';

// The built spec is regenerated by `pnpm run openapi:build`; it contains
// the same operations as openapi/coven.daemon.v1.yaml plus x-codeSamples
// injected by scripts/build-openapi-samples.mjs.
//
// proxyUrl points at the Unix-only docs bridge at
// app/api/coven-proxy/[...path]/route.ts. Native Windows named pipes are not
// supported by this browser-facing bridge.
export const openapi = createOpenAPI({
  input: ['./openapi/coven.daemon.v1.built.yaml'],
  proxyUrl: '/api/coven-proxy',
});
