import { createOpenAPI } from 'fumadocs-openapi/server';

// The built spec is regenerated by `npm run openapi:build`; it contains
// the same operations as openapi/coven.daemon.v1.yaml plus x-codeSamples
// injected by scripts/build-openapi-samples.mjs.
//
// proxyUrl points at the Phase 5 Unix-socket bridge at
// app/api/coven-proxy/[...path]/route.ts, which forwards browser fetches
// to $COVEN_HOME/coven.sock.
export const openapi = createOpenAPI({
  input: ['./openapi/coven.daemon.v1.built.yaml'],
  proxyUrl: '/api/coven-proxy',
});
