import assert from 'node:assert/strict';
import test from 'node:test';
import {
  PLATFORM_SOURCE_PATHS,
  derivePlatforms,
  platformBlockProblems,
  platformTokensFor,
  serializePlatformData,
  validatePlatformData,
} from './platform-data.mjs';

// Fixtures shaped like the upstream files at the pinned commit.
const wrapperPackageJson = JSON.stringify({
  name: '@opencoven/cli',
  optionalDependencies: {
    '@opencoven/cli-macos': '0.0.0',
    '@opencoven/cli-macos-x64': '0.0.0',
    '@opencoven/cli-linux-x64': '0.0.0',
    '@opencoven/cli-windows': '0.0.0',
  },
});

const launcherSource = `
const PLATFORM_PACKAGES = {
  'darwin-arm64': '@opencoven/cli-macos',
  'darwin-x64': '@opencoven/cli-macos-x64',
  'linux-x64': '@opencoven/cli-linux-x64',
  'win32-x64': '@opencoven/cli-windows'
};
`;

const publishSource = `
const targets = {
  macos: {
    packageName: '@opencoven/cli-macos',
    os: 'darwin',
    cpu: 'arm64',
    rustTarget: 'aarch64-apple-darwin',
    binaryName: 'coven',
    // A comment with os: 'nope' after the fields does not leak into the next target.
    helperBinaryName: 'coven-afs-serve'
  },
  'macos-x64': {
    packageName: '@opencoven/cli-macos-x64',
    os: 'darwin',
    cpu: 'x64',
    rustTarget: 'x86_64-apple-darwin',
    binaryName: 'coven'
  },
  'linux-x64': {
    packageName: '@opencoven/cli-linux-x64',
    os: 'linux',
    cpu: 'x64',
    rustTarget: 'x86_64-unknown-linux-gnu',
    binaryName: 'coven'
  },
  windows: {
    packageName: '@opencoven/cli-windows',
    os: 'win32',
    cpu: 'x64',
    rustTarget: 'x86_64-pc-windows-msvc',
    binaryName: 'coven.exe'
  }
};

const nativePackageSets = { 'post-intel': ['macos', 'macos-x64', 'linux-x64', 'windows'] };
`;

const engineLock = `# Generated by scripts/pin-engine.sh — do not edit by hand.
version = "0.8.0"

[sha256]
"coven-code-linux-aarch64.tar.gz" = "${'a'.repeat(64)}"
"coven-code-linux-x86_64.tar.gz" = "${'b'.repeat(64)}"
"coven-code-macos-aarch64.tar.gz" = "${'c'.repeat(64)}"
"coven-code-macos-x86_64.tar.gz" = "${'d'.repeat(64)}"
"coven-code-windows-x86_64.zip" = "${'e'.repeat(64)}"
`;

const sources = { wrapperPackageJson, launcherSource, publishSource, engineLock };
const commit = '1'.repeat(40);
const sourceLock = {
  sources: [{ id: 'coven-runtime-contract', repo: 'OpenCoven/coven', verifiedCommit: commit, paths: [...PLATFORM_SOURCE_PATHS] }],
};

function data(overrides = {}) {
  return JSON.parse(
    serializePlatformData({
      repo: 'OpenCoven/coven',
      verifiedCommit: commit,
      sourceBlobs: PLATFORM_SOURCE_PATHS.map((path, index) => ({ path, blob: String(index + 2).repeat(40) })),
      platforms: derivePlatforms(sources),
      ...overrides,
    }),
  );
}

test('derives every shipped platform in display order', () => {
  const platforms = derivePlatforms(sources);
  assert.deepEqual(
    platforms.map(({ id }) => id),
    ['macos-arm64', 'macos-x64', 'linux-x64', 'linux-arm64', 'windows-x64'],
  );
  assert.deepEqual(platforms[0].cli, {
    package: '@opencoven/cli-macos',
    node: 'darwin-arm64',
    rustTarget: 'aarch64-apple-darwin',
  });
  assert.deepEqual(platforms[4].covenCode, { archive: 'coven-code-windows-x86_64.zip' });
});

test('records Coven Code-only platforms without inventing a CLI package', () => {
  const linuxArm = derivePlatforms(sources).find(({ id }) => id === 'linux-arm64');
  assert.equal(linuxArm.cli, null);
  assert.deepEqual(linuxArm.covenCode, { archive: 'coven-code-linux-aarch64.tar.gz' });
});

test('refuses when the launcher and the release script disagree', () => {
  const launcher = launcherSource.replace("'darwin-x64': '@opencoven/cli-macos-x64'", "'darwin-x64': '@opencoven/cli-macos'");
  assert.throws(() => derivePlatforms({ ...sources, launcherSource: launcher }), /disagree/);
});

test('refuses when the wrapper omits a published package', () => {
  const wrapper = wrapperPackageJson.replace('"@opencoven/cli-windows":"0.0.0"', '');
  assert.throws(() => derivePlatforms({ ...sources, wrapperPackageJson: wrapper.replace(',}', '}') }), /wrapper depends on/);
});

test('refuses a new upstream platform until the docs label it', () => {
  const lock = `${engineLock}"coven-code-windows-aarch64.zip" = "${'f'.repeat(64)}"\n`;
  assert.throws(() => derivePlatforms({ ...sources, engineLock: lock }), /windows-arm64, which has no label/);
});

test('refuses an architecture the docs do not model', () => {
  const lock = `${engineLock}"coven-code-linux-riscv64.tar.gz" = "${'f'.repeat(64)}"\n`;
  assert.throws(() => derivePlatforms({ ...sources, engineLock: lock }), /unknown engine archive/);
});

test('serializes deterministically with a trailing newline', () => {
  const input = {
    repo: 'OpenCoven/coven',
    verifiedCommit: commit,
    sourceBlobs: [...PLATFORM_SOURCE_PATHS].reverse().map((path) => ({ path, blob: '2'.repeat(40) })),
    platforms: derivePlatforms(sources),
  };
  const text = serializePlatformData(input);
  assert.equal(text, serializePlatformData(input));
  assert.ok(text.endsWith('}\n'));
  assert.deepEqual(JSON.parse(text).provenance.sourceBlobs.map(({ path }) => path), PLATFORM_SOURCE_PATHS);
});

test('accepts captured data pinned to the source lock', () => {
  assert.deepEqual(validatePlatformData(data(), sourceLock), []);
});

test('rejects provenance that lags the source lock and names the fix', () => {
  const failures = validatePlatformData(data({ verifiedCommit: '9'.repeat(40) }), sourceLock);
  assert.ok(failures.some((message) => message.includes('capture-platform-data.mjs --write')));
});

test('rejects a source path the drift gate no longer watches', () => {
  const lock = structuredClone(sourceLock);
  lock.sources[0].paths = lock.sources[0].paths.filter((path) => path !== 'scripts/publish-npm.mjs');
  assert.ok(validatePlatformData(data(), lock).some((message) => message.includes('scripts/publish-npm.mjs')));
});

test('rejects hand edits to labels, ids, and order', () => {
  const relabelled = data();
  relabelled.platforms[0].label = 'Mac (M-series)';
  assert.ok(validatePlatformData(relabelled, sourceLock).some((message) => message.includes('label')));

  const duplicated = data();
  duplicated.platforms.push(structuredClone(duplicated.platforms[0]));
  assert.ok(validatePlatformData(duplicated, sourceLock).some((message) => message.includes('unique')));

  const reordered = data();
  reordered.platforms.reverse();
  assert.ok(validatePlatformData(reordered, sourceLock).some((message) => message.includes('order')));
});

test('rejects a CLI entry whose node key does not match its platform', () => {
  const wrong = data();
  wrong.platforms[1].cli.node = 'darwin-arm64';
  assert.ok(validatePlatformData(wrong, sourceLock).some((message) => message.includes('macos-x64 cli')));
});

const knownTokens = platformTokensFor(derivePlatforms(sources));
const fence = '`'.repeat(3);

test('accepts well-formed platform blocks, ignoring fenced code', () => {
  const source = [
    '<Platform only="macos linux">',
    '',
    `${fence}sh`,
    '# a shell comment, not a heading',
    'which -a coven',
    fence,
    '',
    '</Platform>',
    '',
    `${fence}mermaid`,
    'flowchart TD',
    '  Native --> Platform["<Platform only=nope>"]',
    fence,
    '',
    '<Platform only="windows-x64">',
    'Run it in PowerShell.',
    '</Platform>',
  ].join('\n');
  assert.deepEqual(platformBlockProblems(source, knownTokens), []);
});

test('flags headings, nesting, unknown tokens, and unbalanced tags', () => {
  const problems = (source) => platformBlockProblems(source, knownTokens).join('\n');
  assert.match(problems('<Platform only="windows">\n\n### PowerShell\n\n</Platform>'), /line 1: .*contains a heading/);
  assert.match(problems('<Platform only="macos">\n<Platform only="linux">\n</Platform>\n</Platform>'), /line 2: .*nested/);
  assert.match(problems('<Platform only="macOS">\n</Platform>'), /unknown platform "macOS"/);
  assert.match(problems('<Platform>\n</Platform>'), /needs only=/);
  assert.match(problems('<Platform only="linux" />'), /not self-close/);
  assert.match(problems('<Platform only="linux">\ntext'), /never closed/);
  assert.match(problems('text\n</Platform>'), /no opening tag/);
});
